/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.ufpr.contato.view;

import java.awt.event.MouseEvent;
import org.ufpr.contato.model.Contact;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Rafael
 */
public class ContactView extends javax.swing.JFrame {

    
    public ContactView() {
        initComponents();
    }


    public JButton getUpdateButton() {
        return updateButton;
    }

    public JFormattedTextField getBirthdateField() {
        return birthdateField;
    }

    public JTextField getEmailField() {
        return emailField;
    }

    public JTextField getAdressField() {
        return addressField;
    }

    public JButton getDeleteButton() {
        return deleteButton;
    }

    public JButton getCleanButton() {
        return cleanButton;
    }

    public JButton getListButton() {
        return listButton;
    }

    public JTextField getNameField() {
        return nameField;
    }

    public JButton getNewButton() {
        return newButton;
    }

    public JTable getViewTable() {
        return viewTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        listButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        contactFormPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        birthdateLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        birthdateField = new javax.swing.JFormattedTextField();
        emailField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        scrollPanel.setViewportView(viewTable);

        listButton.setText("Listar");

        cleanButton.setText("Limpar");

        deleteButton.setText("Excluir");

        newButton.setText("Novo");

        updateButton.setText("Atualizar");

        nameLabel.setText("Nome:");

        birthdateLabel.setText("Data Nascimento:");

        emailLabel.setText("E-mail:");

        try {
            birthdateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        addressLabel.setText("Endereço:");

        javax.swing.GroupLayout contactFormPanelLayout = new javax.swing.GroupLayout(contactFormPanel);
        contactFormPanel.setLayout(contactFormPanelLayout);
        contactFormPanelLayout.setHorizontalGroup(
            contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactFormPanelLayout.createSequentialGroup()
                .addGroup(contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contactFormPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressField))
                    .addGroup(contactFormPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contactFormPanelLayout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailField))
                            .addGroup(contactFormPanelLayout.createSequentialGroup()
                                .addComponent(birthdateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthdateField))
                            .addGroup(contactFormPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contactFormPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contactFormPanelLayout.setVerticalGroup(
            contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdateLabel)
                    .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(contactFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(updateButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(listButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listButton)
                    .addComponent(cleanButton)
                    .addComponent(deleteButton))
                .addGap(11, 11, 11)
                .addComponent(contactFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showError(String message){
        JOptionPane.showMessageDialog(null,message, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    public Contact getContact(){
        String nome = this.nameField.getText();
        String email = this.emailField.getText();
        String endereco = this.addressField.getText();
        SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(birthdateField.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        Contact contato = new Contact(null,nome,email,endereco,dataNascimento);
        return contato;
    }
        
    public void setContact(Contact contato){
        //Seta os dados nos componentes
        nameField.setText(contato.getName());
        birthdateField.setText(contato.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        emailField.setText(contato.getEmail());
        addressField.setText(contato.getAddress());        
    }
    
    public int getSelectedLine(MouseEvent evt){
        return this.getViewTable().rowAtPoint(evt.getPoint());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JFormattedTextField birthdateField;
    private javax.swing.JLabel birthdateLabel;
    private javax.swing.JButton cleanButton;
    private javax.swing.JPanel contactFormPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton listButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton newButton;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
